# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  glad_config = debug
  SimpleRequest_config = debug

else ifeq ($(config),release)
  glfw_config = release
  glad_config = release
  SimpleRequest_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw glad SimpleRequest

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: glad glfw

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C SimpleRequest/dependencies/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C SimpleRequest/dependencies/glad -f Makefile config=$(glad_config)
endif

SimpleRequest: glfw glad
ifneq (,$(SimpleRequest_config))
	@echo "==== Building SimpleRequest ($(SimpleRequest_config)) ===="
	@${MAKE} --no-print-directory -C SimpleRequest -f Makefile config=$(SimpleRequest_config)
endif

clean:
	@${MAKE} --no-print-directory -C SimpleRequest/dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C SimpleRequest/dependencies/glad -f Makefile clean
	@${MAKE} --no-print-directory -C SimpleRequest -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   SimpleRequest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"